-- AlterTable
ALTER TABLE `Submission` MODIFY `status` ENUM('PENDING', 'PUBLISHED', 'REJECTED', 'REMOVED', 'FAILED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Video` ADD COLUMN `failureReason` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'PUBLISHED', 'REJECTED', 'REMOVED', 'FAILED') NOT NULL DEFAULT 'PENDING';
